In [17]:
import pandas as pd
from openpyxl import load_workbook
from glob import glob

leer un archivo de ejemplo

In [18]:
wb = load_workbook('data/Autoevaluacion_Coevaluacion_AlvaroPerez.xlsx')
# obtener el nombre de las hojas del archivo
print(wb.sheetnames)

['AUTOEVALUACIÓN', 'COEVALUACIÓN']

In [19]:
ws = wb['AUTOEVALUACIÓN']
[i[0].value for i in ws['B4:C4']]

['NOMBRE : Álvaro Matías Pérez Vega']

In [20]:
def leer_autoevaluacion(nombre_archivo):
    name = nombre_archivo.split('_')[-1].replace('.xlsx', '')
    wb = load_workbook(nombre_archivo)
    ws = wb['AUTOEVALUACIÓN']
    estudiante = ' '.join([i[0].value for i in ws['B4:C4']])
    if estudiante == 'NOMBRE : ':
        estudiante = ws[''].value
    estudiante = estudiante.replace('NOMBRE : ', '')
    
    evaluaciones = [
        'trabajo_colaborativo',
        'participacion_actividades',
        'compromisos_tiempo_forma_contenido',
        'dificultades_superar',
        'satisfecho_trabajo'
    ]
    notas = list(map(lambda l: [x.value for x in l][0], ws['D9:D13']))
    autoevaluacion_dict = {
        'estudiante': [name,],
    }
    for i in range(len(evaluaciones)):
        autoevaluacion_dict[evaluaciones[i]] = [notas[i],]
    autoevaluacion_df = pd.DataFrame(autoevaluacion_dict)
    return autoevaluacion_df

In [21]:
leer_autoevaluacion('data/Autoevaluacion_Coevaluacion_AlvaroPerez.xlsx')

,estudiante,trabajo_colaborativo,participacion_actividades,compromisos_tiempo_forma_contenido,dificultades_superar,satisfecho_trabajo
0,AlvaroPerez,6,7,6,5,6

Leer todas las autoevaluaciones

In [22]:
df = pd.DataFrame()
for archivo in glob('data/*.xlsx'):
    if not archivo.startswith('data/~$'):
        df = pd.concat([df, leer_autoevaluacion(archivo)])
df.reset_index(drop=True)
df

/var/folders/ch/j3x8qgtx01jftwmp8jjy91yc0000gn/T/ipykernel_56088/1544936191.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, leer_autoevaluacion(archivo)])

,estudiante,trabajo_colaborativo,participacion_actividades,compromisos_tiempo_forma_contenido,dificultades_superar,satisfecho_trabajo
0,RodrigoPasten,5.0,5.0,4.0,7.0,5.0
0,ClaudiaBlancoM,5.0,5.0,5.0,7.0,7.0
0,BraulioQuiroz,7.0,7.0,7.0,7.0,7.0
0,MayerlynRodriguez,7.0,7.0,7.0,7.0,7.0
0,AlvaroPerez,6.0,7.0,6.0,5.0,6.0
0,FelixGonzalez,7.0,7.0,7.0,7.0,7.0
0,OscarTorres,6.8,6.5,7.0,6.8,6.8
0,FlavioJara,7.0,6.0,6.0,7.0,5.0
0,CamilaOyarzún,6.0,6.6,6.5,7.0,7.0
0,Geraldy Suarez,7.0,7.0,7.0,7.0,7.0
0,YerkoGallardo,6.0,6.0,5.0,6.0,5.0
0,RodrigoAlvarez,5.0,7.0,7.0,7.0,6.0
0,PauloRamirez,5.0,5.0,7.0,7.0,6.0
0,BryanCastillo,7.0,7.0,6.5,4.5,5.5
0,RodrigoAraya,7.0,6.5,7.0,6.5,6.5
0,HectorAguayo,7.0,5.0,7.0,7.0,7.0
0,EstefaniaManriquez,6.5,6.7,6.7,7.0,7.0
0,BianelBianchini,7.0,7.0,7.0,7.0,7.0
0,PabloUribe,7.0,7.0,7.0,7.0,7.0
0,CristianChavezJara,7.0,7.0,6.0,5.0,5.0
0,BastiánGamboa,6.5,6.3,6.5,7.0,6.0
0,RubenSanhueza,7.0,7.0,7.0,7.0,7.0
0,FabianDiaz,7.0,7.0,7.0,7.0,7.0
0,PatricioVera,6.9,6.8,6.8,6.9,6.9
0,DanielaMendez,4.0,4.0,4.0,4.0,4.0
0,ArielInostroza,6.0,7.0,7.0,7.0,7.0
0,SebastianVega,6.0,7.0,6.0,7.0,7.0
0,CristobalQuiroz,6.0,7.0,6.0,7.0,7.0
0,ManuelDenis,7.0,6.5,7.0,7.0,7.0
0,JuanVega,7.0,7.0,7.0,7.0,7.0
0,UlisesCampodonico,7.0,7.0,6.0,6.0,6.0
0,VíctorMeza,7.0,7.0,7.0,7.0,6.0
0,DanielaPorto,NaN,NaN,NaN,NaN,NaN
0,ScarlettEspinoza,7.0,7.0,7.0,7.0,7.0
0,NicolasRojas,7.0,7.0,7.0,7.0,7.0
0,StefanyaPulgar,6.0,6.0,7.0,7.0,6.0
0,ArielMora,7.0,7.0,7.0,7.0,7.0

### Coevaluación

Prueba con un archivo

In [28]:
wb = load_workbook('data/Autoevaluacion_Coevaluacion_AlvaroPerez.xlsx')
# obtener el nombre de las hojas del archivo
print(wb.sheetnames)
ws = wb['AUTOEVALUACIÓN']
ws_coevaluacion = wb['COEVALUACIÓN']

['AUTOEVALUACIÓN', 'COEVALUACIÓN']

In [30]:
co_evaluaciones = [
    'Participó activamente en el trabajo colaborativo',
    'Participó con entusiasmo en las actividades del curso',
    'Entregó sus compromisos en tiempo, forma y contenido dentro del trabajo grupal',
    'Se esforzó en superar sus dificultades',
    'Me siento satisfecho(a) con el trabajo que el(ella) ha realizado'
]

estudiante = ' '.join([i[0].value for i in ws['B4:C4']])
estudiante = estudiante.replace('NOMBRE :', '')
companeros = list(map(lambda l: [x.value for x in l], ws_coevaluacion['H9:N9']))[0]
notas = list(map(lambda l: [x.value for x in l], ws_coevaluacion['H10:N14']))
notas_dict = {
    'companeros': companeros,
    'evaluador':[estudiante] * len(companeros)
}
for i in range(len(co_evaluaciones)):
    notas_dict[co_evaluaciones[i]] = notas[i]
notas_df = pd.DataFrame(notas_dict)
notas_df.head()

,companeros,evaluador,Participó activamente en el trabajo colaborativo,Participó con entusiasmo en las actividades del curso,"Entregó sus compromisos en tiempo, forma y contenido dentro del trabajo grupal",Se esforzó en superar sus dificultades,Me siento satisfecho(a) con el trabajo que el(ella) ha realizado
0,Daniela Méndez Gándara,Álvaro Matías Pérez Vega,4.0,4.0,4.0,5.0,4.0
1,Pedro Nahum,Álvaro Matías Pérez Vega,6.0,7.0,6.0,6.0,6.0
2,Javier Gajardo,Álvaro Matías Pérez Vega,7.0,7.0,7.0,7.0,7.0
3,Ángela Proboste Neira,Álvaro Matías Pérez Vega,1.0,1.0,1.0,1.0,1.0
4,Nicolás Guzmán,Álvaro Matías Pérez Vega,6.0,6.0,7.0,6.0,6.0

In [31]:
def leer_coevaluacion(nombre_archivo):
    wb = load_workbook(nombre_archivo)
    ws_coevaluacion = wb['COEVALUACIÓN']
    ws = wb['AUTOEVALUACIÓN']
    estudiante = ' '.join([i[0].value for i in ws['B4:C4']])
    estudiante = estudiante.replace('NOMBRE :', '')
    companeros = list(map(lambda l: [x.value for x in l], ws_coevaluacion['H9:N9']))[0]
    notas = list(map(lambda l: [x.value for x in l], ws_coevaluacion['H10:N14']))
    notas_dict = {
        'companeros': companeros,
        'evaluador':[estudiante] * len(companeros)
    }
    for i in range(len(co_evaluaciones)):
        notas_dict[co_evaluaciones[i]] = notas[i]
    notas_df = pd.DataFrame(notas_dict)
    return notas_df

In [32]:
leer_coevaluacion('data/Autoevaluacion_Coevaluacion_AlvaroPerez.xlsx')

,companeros,evaluador,Participó activamente en el trabajo colaborativo,Participó con entusiasmo en las actividades del curso,"Entregó sus compromisos en tiempo, forma y contenido dentro del trabajo grupal",Se esforzó en superar sus dificultades,Me siento satisfecho(a) con el trabajo que el(ella) ha realizado
0,Daniela Méndez Gándara,Álvaro Matías Pérez Vega,4.0,4.0,4.0,5.0,4.0
1,Pedro Nahum,Álvaro Matías Pérez Vega,6.0,7.0,6.0,6.0,6.0
2,Javier Gajardo,Álvaro Matías Pérez Vega,7.0,7.0,7.0,7.0,7.0
3,Ángela Proboste Neira,Álvaro Matías Pérez Vega,1.0,1.0,1.0,1.0,1.0
4,Nicolás Guzmán,Álvaro Matías Pérez Vega,6.0,6.0,7.0,6.0,6.0
5,integrante 6,Álvaro Matías Pérez Vega,NaN,NaN,NaN,NaN,NaN
6,integrante 7,Álvaro Matías Pérez Vega,NaN,NaN,NaN,NaN,NaN

Leer todas las coevaluaciones

In [33]:
df_coevaluacion = pd.DataFrame()
for archivo in glob('data/*.xlsx'):
    if not archivo.startswith('data/~$'):
        df_coevaluacion = pd.concat([df_coevaluacion, leer_coevaluacion(archivo)])
df_coevaluacion.reset_index(drop=True)
df_coevaluacion

,companeros,evaluador,Participó activamente en el trabajo colaborativo,Participó con entusiasmo en las actividades del curso,"Entregó sus compromisos en tiempo, forma y contenido dentro del trabajo grupal",Se esforzó en superar sus dificultades,Me siento satisfecho(a) con el trabajo que el(ella) ha realizado
0,Juan Salinas,,4.0,3.0,3.0,2.0,2.0
1,Daniel García,,2.0,2.0,2.0,1.0,1.0
2,Fabian Diaz,,4.0,3.0,4.0,4.0,4.0
3,Natalia Rivera,,5.0,4.0,4.0,4.0,3.0
4,Flavio Jara,,5.0,5.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...
2,Claudia Blanco,ARIEL MORA,6.5,6.5,6.5,6.5,6.0
3,Héctor Aguayo,ARIEL MORA,7.0,7.0,7.0,7.0,7.0
4,Ruben Sanhueza,ARIEL MORA,7.0,7.0,7.0,7.0,7.0
5,integrante 6,ARIEL MORA,NaN,NaN,NaN,NaN,NaN
6,integrante 7,ARIEL MORA,NaN,NaN,NaN,NaN,NaN